# Generated by Django 2.1.15 on 2020-05-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200519_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='universe',
            field=models.CharField(max_length=255),
        ),
    ]
