# Generated by Django 2.1.15 on 2020-05-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200519_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='superpowers',
            field=models.ManyToManyField(to='core.SuperPower'),
        ),
    ]
