# Generated by Django 2.1.15 on 2020-05-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200519_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='universe',
            field=models.CharField(choices=[('Marvel', 'Marvel'), ('DC', 'DC')], max_length=255),
        ),
    ]
